[package]
name = "ethproofs_verifier"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
base64 = "0.21.7"
bincode = { version = "2", features = ["serde"] }

cli = {git = "https://github.com/matter-labs/zksync-airbender", tag = "dev-v0.7.0"}
verifier_common = {git = "https://github.com/matter-labs/zksync-airbender", tag = "dev-v0.7.0"}
full_statement_verifier = {git = "https://github.com/matter-labs/zksync-airbender", tag = "dev-v0.7.0"}


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
overflow-checks = true
incremental = true